# Introduction

[My Profile](https://ctang.netlify.app/), please send me email. 


**Combinatorics** is essentially the art of avoiding overcounting while ensuring completeness.

组合计数
1. 基础计数： 处理元素与容器的区分度（球盒模型）- Twelvefold Way
   1.  If objects are labeled, we are dealing with functions ($f: A \to B$). Grounded in set theory and exponential growth ($m^n$).
   2.  If objects are labeled, we are no longer mapping specific elements; we are simply partitioning integers.
2. 约束计数： 处理容斥问题、抽屉原理（约束条件）、生成函数。
   1. If you can pick 0, 1, or 2 oranges, you write $(1 + x^1 + x^2)$. 
   2. If you have 3 boxes, you calculate $(1 + x + x^2)^3$. The coefficient of $x^n$ is your answer.
3. 等价计数： 处理群论下的对称性 Burnside's Lemma & Pólya Enumeration Theorem (PET)。
   1. **Orbits** (the "stacms" of equivalent states)
   2. **Burnside** is the "global" view: To find the number of unique objects, you find the average number of states that remain "fixed" (unchanged) under each symmetry operation.
   3. **Pólya** (PET) is the "local" view: It uses the Cycle form. If a rotation of a necmlace swaps beads in cycles of length 2, you can choose any color for each cycle, not each bead. PET allows you to weight these colors, giving you a generating function for unique colored objects.



Counting levels|- Obstacle <br> - Goal|Focus|Tools
|:-:|-|-|-|
Fundamental <br> *building*|- Identity ambiguity <br> - labeled or not (Set Theory / Functions)|Twelvefold Way |Objects labelled: You are counting Functions. <br> Objects unlabelled: You are counting Occupancy Numbers.
Constrained <br> *filtering*|- Overlapping restrictions <br> - Apply "Filters" to the raw count.| Sieving(IEP), Number Theory, Series | Inclusion-Exclusion Principle(Derangements $!n$ 错排问题); <br>Pigeonhole Principle(抽屉原理); <br>Generating Functions; <br>Stars and Bars(隔板法)
Equivalence <br> *topological*|- Redundancy from dynamic/topological, not static like above <br> - To eliminate duplicates caused by rotation or flipping.  |Symmetry/Groups| count Orbits under a Group Action.

### Twelvefold Way -> 二十四路计数

|f-class | Ball $N$ <b> Box $M$ | $f$ unrestricted | $f$ one-to-one injective| $f$ onto Surjective|
|-|--|:---:|:---:|:---:|
|f| ball labeled <br> box labeled | 1: Tuple | 2: Permu | 3: Stir |
|$f\circ S_n$| ball unlabeled <br> box labeled | 4: w-Comp | 5: Binom | 6: Comp |
|$S_m \circ f$| ball labeled <br> box unlabeled | 7: Stir | 8: Ordin | 9: Stir |
|$S_m \circ f\circ S_n$| ballunlabeled <br> box unlabeled | 10: GF | 11: Ordin | 12: GF |


Structural summary
  - Stirling numbers = unlabeled blocks
  - Bell numbers = all partitions
  - Partitions = size-only structure

**Bell数**的整数数列：B0=1,B1=1,B2=2,B3=5,B4=15,B5=52,B6=203.... , Bn是基数为n的集合的划分方法数目。
- 集合S的一个划分partition是定义为S的两两不相交的非空子集的族，他们的并是S。
- B3=5，集合S={1,2,3}的划分就是: 
{{1},{2},{3}}
{{1,2},{3}}
{{1,3},{2}}
{{2,3},{1}}
{{1,2,3}}.

**第二类Stirling数**{S(n, k)}：将 n 个不同元素分到 k 个相同非空集合中的方法数。 
- S(3, 2) = 3，将 {1, 2, 3} 分为 2 个非空集，有 {{1,2},{3}}, {{1,3},{2}}, {{1},{2,3}} 三种方案。
- 递推公式为：
S(n,n+1)=0
S(n,0)=0
S(0,0)=1
S(n,k)=kS(n-1,k)+S(n-1,k-1)
- Bell数 =$\sum$ 每行S(n,k)

| n\k| 0|1|2|3|4|5
|---|---|---|---|---|-|-|
|0|1|0|0|0|0|0|
|1|0|1|0|0|0|0|
|2|0|1|1|0|0|0|
|3|0|1|3|1|0|0|
|4|0|1|7|6|1|0|
|5|0|1|15|25|10|1|

**Partition分拆函数** p(n)，从 n=0开始的序列是 1, 1, 2, 3, 5, 7, 11, 15, 22, 30, 42, 56, 77, ..
定义：数字n被拆分成多少种不同组合（不考虑顺序）。
- n=3共有 3 种分拆：3, 2+1, 1+1+1，p(3)=3
- n=4共有 5 种分拆：4, 3+1, 2+2, 2+1+1, 1+1+1+1，p(4)=5



|f-class | Ball $N$ <b> Box $M$ | $f$ unrestricted | $f$ one-to-one injective| $f$ onto Surjective|
|-|--|---|---|---|
|f| ball labeled <br> box labeled | $m^n$ | $(m-n+1)_n$ | $m!\,S(n,m)$ |
|$f\circ S_n$| ball unlabeled <br> box labeled | $\binom{m+n-1}{n}$ | $\binom{m}{n}$ | $\binom{n-1}{\,n-m\,}$ |
|$S_m \circ f$| ball labeled <br> box unlabeled | $S(n,1)+S(n,2)+\cdots+S(n,m)$ | $\begin{cases}1 & n\le m\\0 & n>m\end{cases}$ | $S(n,m)$ |
|$S_m \circ f\circ S_n$| ballunlabeled <br> box unlabeled | $p_m(n)$ | $\begin{cases}1 & n\le m\\0 & n>m\end{cases}$ | $p_m(n)-p_{m-1}(n)$ |

- $S_m, S_n$: Symmetric/permutation groups acting on balls and boxes, respectively. The "$\circ$" is the group action (composition/transformation)


btw: Stirling arise from both permutation & set partitions

```mermaid
flowchart LR
    A["Finite set {1,2,3,4,5}"] --> B[Partition into k blocks]
    A --> C[Permutation]

    %% Set partitions
    B --> B1["Block 1: {1,3,5}"]
    B --> B2["Block 2: {2,4}"]
    B1 --> D["S(n,k)"]
    B2 --> D

    %% Permutation cycles
    C --> C1["Cycle: (1 3 5)"]
    C --> C2["Cycle: (2 4)"]
    C1 --> E["c(n,k)"]
    C2 --> E

    %% Conceptual bridge
    D --> F[Unlabeled components]
    E --> F

    F --> G[Same decomposition into k components]


In [ ]:
# Twelvefold Way in SageMath (n balls --> k boxes)
def TF_distinctBalls_labeledBoxes(n, k): #     Balls distinct/labeled, boxes labeled.
    any = k^n                                                 # k^n , unrestricted
    inj = 0 if n > k else factorial(k) // factorial(k - n)    # (k)_n, falling_factorial(k,n)
    sur = factorial(k) * stirling_number2(n, k)               # k! S(n,k)
    return any, inj, sur

def TF_identicalBalls_labeledBoxes(n, k): # Occupancy is vector
    any = binomial(n + k - 1, k - 1)              # xi>=0, sum=n -> stars and bars C(n+k-1,k-1)
    inj = 0 if n > k else binomial(k, n)          # xi in {0,1}, sum=n -> choose n boxes
    sur = 0 if n < k else binomial(n - 1, k - 1)  # xi>=1, sum=n -> compositions count C(n-1,k-1)
    return any, inj, sur

def TF_distinctBalls_unlabeledBoxes(n, k): #   Balls distinct, boxes unlabeled/identical
    any = sum(stirling_number2(n, i) for i in range(0, k+1)) # set partitions into <= k blocks -> sum_{i=0..k} S(n,i)
    inj = 1 if n <= k else 0     # all balls separated (possible iff n<=k)
    sur = stirling_number2(n, k) # set partitions into exactly k blocks -> S(n,k)
    return any, inj, sur

def TF_identicalBalls_unlabeledBoxes(n, k): # Occupancy is a partition (multiset of block sizes)
    any = Partitions(n, max_length=k).cardinality()  # partitions of n into <= k parts -> p_{<=k}(n)
    inj = 1 if n <= k else 0                         # pattern is 1+...+1 (n ones) (possible iff n<=k)
    sur = 0 if n < k else Partitions(n, length=k).cardinality() # partitions of n into k positive parts -> p_k(n)
    return any, inj, sur

def twelvefold_summary(n, k): # print a neat 12-way summary for given n,k
    db_lb = TF_distinctBalls_labeledBoxes(n, k)
    db_ub = TF_distinctBalls_unlabeledBoxes(n, k)
    ib_lb = TF_identicalBalls_labeledBoxes(n, k)
    ib_ub = TF_identicalBalls_unlabeledBoxes(n, k)
    print("")
    print("Twelvefold way (", n, "balls, ",k, "boxes) with capacity rule:")
    print("1) Balls labeled,   Boxes labeled:   Any:", db_lb[0], "  Inj:", db_lb[1], "  Sur:", db_lb[2])
    print("2) Balls labeled,   Boxes unlabeled: Any:", db_ub[0], "  Inj:", db_ub[1], "  Sur:", db_ub[2])
    print("3) Balls unlabeled, Boxes labeled:   Any:", ib_lb[0], "  Inj:", ib_lb[1], "  Sur:", ib_lb[2])
    print("4) Balls unlabeled, Boxes unlabeled: Any:", ib_ub[0], "  Inj:", ib_ub[1], "  Sur:", ib_ub[2])

# Optional: small brute checks (useful for sanity for small n,k)
def brute_distinctBalls_labeledBoxes_any(n, k):
    return k^n      # Count all functions [n]->[k]
def brute_distinctBalls_labeledBoxes_inj(n, k):
    if n > k: return 0      # injections = permutations of k choose n = (k)_n
    return factorial(k) // factorial(k - n)
def brute_distinctBalls_labeledBoxes_sur(n, k):
    return factorial(k) * stirling_number2(n, k) # surj count via Stirling is already exact; brute is expensive

# 3 examples 
print("           Any=unrestricted;   Injective=no multi-balls;  Surjective=no empty box")
twelvefold_summary(5, 5) # it is bijective 
twelvefold_summary(5, 3)
twelvefold_summary(5, 6)

           Any=unrestricted;   Injective=no multi-balls;  Surjective=no empty box

Twelvefold way ( 5 balls,  5 boxes) with capacity rule:
1) Balls labeled,   Boxes labeled:   Any: 3125   Inj: 120   Sur: 120
2) Balls labeled,   Boxes unlabeled: Any: 52   Inj: 1   Sur: 1
3) Balls unlabeled, Boxes labeled:   Any: 126   Inj: 1   Sur: 1
4) Balls unlabeled, Boxes unlabeled: Any: 7   Inj: 1   Sur: 1

Twelvefold way ( 5 balls,  3 boxes) with capacity rule:
1) Balls labeled,   Boxes labeled:   Any: 243   Inj: 0   Sur: 150
2) Balls labeled,   Boxes unlabeled: Any: 41   Inj: 0   Sur: 25
3) Balls unlabeled, Boxes labeled:   Any: 21   Inj: 0   Sur: 6
4) Balls unlabeled, Boxes unlabeled: Any: 5   Inj: 0   Sur: 2

Twelvefold way ( 5 balls,  6 boxes) with capacity rule:
1) Balls labeled,   Boxes labeled:   Any: 7776   Inj: 720   Sur: 0
2) Balls labeled,   Boxes unlabeled: Any: 52   Inj: 1   Sur: 0
3) Balls unlabeled, Boxes labeled:   Any: 252   Inj: 6   Sur: 0
4) Balls unlabeled, Boxes unlabeled: Any

### 二十四路计数


三个逻辑维度 - 比 12 路多一个
- 元素（球）是否可区分？ (Distinguishable / Indistinguishable)
- 容器（盒）是否可区分？ (Distinguishable / Indistinguishable)
- 容器内的元素是否有序？ (Ordered / Unordered) —— 这是 24 路相比 12 路增加的关键维度

ps: 12fold Way是所有计数的核心，“有序”情况(即24路)可以通过“先分组、再排列”推导出来

球是否相同|盒是否相同|盒内是否有序|无限制 (L)|单射 (I)|满射 (S)
|-|-|-|-|-|-|
不同|不同|无序|m^n|"P(m,n)"|"m!S2​(n,m)"
相同|不同|无序|"C(n+m−1,m−1)"|"C(m,n)"|"C(n−1,m−1)"
不同|相同|无序|"∑S2​(n,k)"|[n≤m]|"S2​(n,m)"
相同|相同|无序|"p(n,m)"|[n≤m]|"p(n−m,m)"
不同|不同|有序|"P(n+m−1,n)"|"P(m,n)"|"n!C(n−1,m−1)"
不同|相同|有序|(分配并除以 m!)|[n≤m]|(同左)

### 格路径

Combinatorial Object | Start-End| Allowed Steps| Boundary | Lattice Path Model - Notes
|:-:|-|-|-|-|
Binomial coefficients $\binom{a+b}{a}$|(0,0)-->(a,b)|R(1,0), U(0,1)|None| Rectangular grid paths in 2D
Multinomial coeff<br>$\binom{n}{k_1, \dots, k_d}$|**0**-->($k_1\dots, k_d$)|Unit step vector|None|Generalization to d-dimensional grid.
Catalan numbers<br> $C_n = \frac{1}{n+1} \binom{2n}{n}$|(0,0)-->(n,n)|R(1,0), U(0,1)|$y\leq x$ (stay on or below diagonal)|Dyck paths in rotated or grid form.
Narayana <br>$N(n,k)=\frac{1}{n}\binom{n}{k}\binom{n}{k-1}$|(0,0)-->(n,n)| R(1,0), U(0,1)| $y\leq x$, exactly k peaks (rigid up-right step in grid)| Dyck paths with exactly $k$ peaks, refines Catalan numbers; $\sum_k N(n,k) = C_n$.
Delannoy<br> $D(a,b)$ | (0,0)-->(a,b)| R(1,0), U(0,1), D(1,1)| None| Binomial --> + diagonal steps
Large Schröder<br> $r_n$ or $S_n$| (0,0)-->(n,n)| R(1,0), U(0,1), D(1,1)| $y\leq x$ (stay on or below diagonal)|Catalan --> + diagonal steps.
Motzkin<br>  $M_n$| (0,0)-->(n,0)| Level (1,0), U(1,1), Down(1,-1)| Height $y\geq 0$ always| Motzkin paths interpolate between Dyck (no level steps) and Schröder paths. <br>Paths never go below ground and allow level steps at any height.
Stirling(2nd)<br> $S(n,k)$| (0,0)-->Ends at height $k$ after $n$ steps| Horizontal: add element to an existing block.<br>Vertical: start a new block<br>Diagonal: start a new block and immediately populate it| No horizontal step at height 0 (blocks are never empty)| Models building set partitions (Paths of length $n$ encoding block construction).
Bell numbers<br> $B_n = \sum_k S(n,k)$| (0,0)-->Any endpoint consistent with total length n| same as above| No horizontal steps at height 0| Same as Stirling(2nd), but summing over all final heights $k$. <br>All valid block-creation paths of length $n$

R=Right, U=Up, D=Diagonal

Step-set enrichment:
- Binomial → Delannoy → Schröder
-Dyck → Motzkin → Schröder

Boundary refinement:
- None → half-plane constraint → statistic-refined subclasses (Narayana)

Combinatorial meaning of boundaries:
- Diagonal constraint: balance / nonnegativity (stacks, parentheses, trees)
- No horizontal at zero: forbids empty structures (non-empty blocks)

Exponential vs ordinary structures:
- Catalan / Motzkin / Schröder: recursive (tree-like)
- Stirling / Bell: set-like, exponential combinatorics encoded by paths

### Poker 

In [ ]:
############ Poker Simulator ############
Hua=Set(["Hearts","Diamonds","Spades","Clubs"])
Num=Set([2,3,4,5,6,7,8,9,10,"J","Q","K","A"])
Card=cartesian_product([Hua, Num]) # 4*13=52
print(Card)

s(Hua.cardinality())
s(Num.cardinality())
s(Card.cardinality())

s(Card.random_element())                      # pick up a card randomly
Set([Card.random_element(),Card.random_element()]) # two cards randomly

In [ ]:
Hands=Subsets(Card, 5)  # Five-cards game
s(Hands.random_element())
Hands.cardinality()==binomial(52,5)

Subsets(Num,5).cardinality()==binomial(13,5)    # 1287
Flushes=cartesian_product([Subsets(Num,5),Hua]) # 1287*4=5148 
s(Flushes.random_element())
Flushes.cardinality()/Hands.cardinality() # probabilty of the same Hua

### Subsets

In [ ]:
s(binomial(4,2))
A=Subsets([1,2,3,4],2); s(A.cardinality())
s(A.list())
s(A.unrank(1)) # display item (1)
s(A[1]==A.unrank(1))

In [ ]:
A=Set([1,2,3,4]); Nest=Subsets(Subsets(A)) # nested
s(Nest.cardinality())
#s(Nest.list())

### Integer partition & composition & permutation(updating)

In [ ]:
P5=Partitions(5);s(P5)
s(P5.cardinality())
P5.list() # compared to Compositions(), order not exist

<IPython.core.display.Math object>

<IPython.core.display.Math object>

[[5], [4, 1], [3, 2], [3, 1, 1], [2, 2, 1], [2, 1, 1, 1], [1, 1, 1, 1, 1]]

In [ ]:
Partitions(999).cardinality()

In [ ]:
P7=Partitions(7)
p=P7.unrank(5)
s(p.ferrers_diagram())
p

In [ ]:
Partition([4,2,1]) # no 's'
WeightedIntegerVectors(8,[2,3,5]).list()

In [ ]:
C5=Compositions(5); s(C5.cardinality()); s(C5.list()) # compared to Partitions(), order matters
s([Compositions(n).cardinality() for n in range(10)])
var('x')
s(sum(x^len(c) for c in C5 ))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [ ]:
C=IntegerRange(3,21,2); s(C); s(C.cardinality()); s(C.list())

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [ ]:
C=Permutations(4); s(C.cardinality()); s(C.list())

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [ ]:
C=SetPartitions(["a","b","c"]); s(C.cardinality()); s(C.list())

<IPython.core.display.Math object>

<IPython.core.display.Math object>

### GF 4 enumeration tree

In [ ]:
############ Start from an Integer Seq, to find out GF ############
oeis([1,1,2,5,14])

In [ ]:
# to verify A000108
var('C, z')
# method 1
sys = [C == z + C*C]
s(sys)
sol = solve(sys, C, solution_dict=True) ; #s(sol)
s0=sol[0][C]; s1=sol[1][C]
#s(s0.series(z,6), s1.series(z,6))  # Tylor series, [1][C] is wrong
#C=s0; s(C.series(z,11)); s(C.series(z,101).coefficient(z,100))

# method 2
L.<z>=LazyPowerSeriesRing(QQ)
C=L.undefined(valuation=1)
C.define(z + C*C)
s([C.coefficient(i) for i in range(11)])

z=var('z') # back to closure-type C(z)
C=s0; s(C)
s(derivative(C,z,1))

def d(n): return derivative(s0,n).subs(z=0)
[d(n+1)/d(n) for n in range(1,17)]  # d(n+1)/d(n) = 4n-2 , so C(n+1)/C(n) = (4n-2)/(n+1)

$$c_n = Catalan(n-1) = \frac{1}{n} \binom{2(n-1)}{n-1}$$

In [ ]:
n=var('n')
c=1/n*binomial(2*(n-1),n-1)
s([c.subs(n=k)         for k in range(1,11)])
s([catalan_number(k-1) for k in range(1,11)])

## OEIS 11 core sequences

[11 categories of "Core Sequences" ](https://oeis.org/wiki/Index_to_OEIS:_Section_Cor#core)
- 1 - 3: Foundations & "Superstars". Contain the most ubiquitous sequences in mathematics, especially discrete math
- 4 - 5: Geometry, Powers & Forms. Bridges the gap btw pure arithmetic and geometric shapes or complex analysis.
- 6 - 8: Constants, Graphs & Distribution. Intersection of discrete graph theory with continuous analysis constants.
- 9 - 11: Number Properties & Special Functions. Categorize numbers by their intrinsic properties and provide the tools for calculus and analysis.

Foundations & "Superstars"| List
|-|-|
|1. Axiomatic & Algebraic Basics: Fundamental building blocks of math. This group defines the basics of counting (Natural numbers, 0s, 1s) and the primary structures of Abstract Algebra (Groups, Permutation Groups). It also introduces elementary Number Theory via Divisors and Totients. | A000001 (groups), A000002 (Kolakoski), A000004 (0's), A000005 (divisors), A000007 (0^n), A000009 (distinct partitions), A000010 (totient), A000012 (1's), A000014 (series-reduced trees), A000019 (prim. perm. groups), A000027 (natural numbers), A000029 (necklaces), A000031 (necklaces), A000032 (Lucas), A000035 (0101...) 
|2. Primes & Recurrences: most famous sequences in history. It holds the primary objects of Number Theory (Primes, Mersenne primes) and the most famous recurrence relations (Fibonacci) and combinatorial counts (Catalan numbers, Partitions). | A000040 (primes), A000041 (partitions), A000043 (Mersenne), A000045 (Fibonacci), A000048 (necklaces), A000055 (trees), A000058 (Sylvester), A000069 (odious), A000079 (2^n), A000081 (rooted trees), A000085 (self-inverse perms.), A000088 (graphs), A000105 (polyominoes), A000108 (Catalan), A000109 (polyhedra)
|3. Enumerative Combinatorics: Counting ways to arrange objects. Focused on "How many ways can we...?" problems. It covers set partitions (Bell numbers), orderings (Factorials), and derangements (shuffling where nothing stays in place).|A000110 (Bell), A000111 (Euler), A000112 (posets), A000120 (1's in n), A000123 (binary partitions), A000124 (Lazy Caterer), A000129 (Pell), A000140 (Kendall-Mann), A000142 (n!), A000161 (partitions into 2 squares), A000166 (derangements), A000169 (labeled rooted trees)

Geometry, Powers & Forms| List
|-|-|
|4. Geometric Numbers & Arithmetic Functions: Numbers that form shapes and measure size. Contains "Figurate Numbers" (Triangular, Tetrahedral) which arrange dots in geometric shapes. It also includes functions that sum parts of numbers (Sigma) and basic powers (2^n,3^n).|A000182 (tangent), A000203 (sigma), A000204 (Lucas), A000217 (triangular), A000219 (planar partitions), A000225 (2^n-1), A000244 (3^n), A000262 (sets of lists), A000272 (n^(n-2)), A000273 (directed graphs), A000290 (n^2), A000292 (tetrahedral)
|5. Higher Forms & Modular Theory (arithmetic and complex analysis): Advanced structures and Physics connections. Moves into higher-dimensional figurate numbers (Pyramidal) and deep number theory objects like Modular Forms (j-invariant, Ramanujan's τ), which connect to String Theory and Elliptic Curves.|A000302 (4^n), A000311 (Schroeder's fourth), A000312 (mappings), A000326 (pentagonal), A000330 (square pyramidal), A000364 (Euler or secant), A000396 (perfect), A000521 (j), A000578 (n^3), A000583 (n^4), A000593 (sum odd divisors), A000594 (Ramanujan tau), A000602 (hydrocarbons), A000609 (threshold functions), A000670 (preferential arrangements)


Constants, Graphs & Distribution| List
|-|-|
|6. Universal Constants & Algebra: The bridge between Discrete and Continuous. Features the fundamental constants of the universe (π,e) alongside deep algebraic classifications (Simple Groups) and prime distribution functions (π(n)).|A000688 (abelian groups), A000720 (pi(n)), A000793 (Landau), A000796 (Pi), A000798 (quasi-orders or topologies), A000959 (Lucky), A000961 (prime powers), A000984 (binomial(2n,n)), A001003 (Schroeder's second problem), A001006 (Motzkin), A001034 (simple groups), A001037 (irreducible polynomials), A001045 (Jacobsthal), A001055 (multiplicative partition function), A001065 (sum of divisors), A001057 (all integers), A001097 (twin primes), A001113 (e), A001147 (double factorials), A001157 (sum of squares of divisors), A001190 (Wedderburn-Etherington), A001221 (omega), A001222 (Omega), A001227 (odd divisors), A001285 (Thue-Morse), A001333 (sqrt(2))
|7. Graph Theory & Recursion: Nodes, Edges, and Self-Reference. Heavily focused on Graph Theory (Connected graphs, Binary trees) and recursive sequences that reference themselves (Golomb sequence).|A001349 (connected graphs), A001358 (semiprimes), A001405 (binomial(n,n/2)), A001462 (Golomb), A001477 (integers), A001478 (negatives), A001481 (sums of 2 squares), A001489 (negatives), A001511 (ruler function), A001615 (sublattices), A001699 (binary trees), A001700 (binomial(2n+1, n+1)), A001519 (Fib. bisection),A001764 (C3n,n)/(2n+1)), A001906 (Fib. bisection), A001969 (evil), A002033 (perfect partitions), A002083 (Narayana-Zidek-Capell), A002106 (transitive perm. groups), A002110 (primorials), A002113 (palindromes), A002275 (repunits)
|8. Lattices & Roots: Grids and Irrationals. Focuses on structures defined on grids (Lattices, Planar graphs) and the expansion of irrational roots, which relate to Diophantine approximations.|A002322 (psi), A002378 (pronic), A002426 (central trinomial coefficients), A002487 (Stern), A002530 (sqrt(3)), A002531 (sqrt(3)), A002572 (binary rooted trees), A002620 (quarter-squares), A002654 (re: sums of squares), A002658 (3-trees), A002808 (composites), A003094 (connected planar graphs), A003136 (Loeschian), A003418 (LCM), A003484 (Hurwitz-Radon), A004011 (D_4), A004018 (square lattice)

Number Properties & Special Functions | List
|-|-|
|9. "Zoology" of Numbers: Classifying integers by their "personality." Sorts numbers based on the sum of their factors (Abundant, Deficient, Perfect) or their prime factors (Squarefree). It treats numbers like biological specimens with distinct traits.|A004526 (ints repeated), A005036 (dissections), A005100 (deficient), A005101 (abundant), A005117 (squarefree), A005130 (Robbins), A005230 (Stern), A005408 (odd), A005470 (planar graphs), A005588 (binary rooted trees), A005811 (runs in n), A005843 (even), A006318 (royal paths or Schroeder numbers), A006530 (largest prime factor)
|10. Calculus Toolkit (Coefficients): Tools for expansions and series. This is the "Engine Room" of analysis. It contains the coefficients used in Taylor series and finite differences: Pascal's Triangle (Binomial), Stirling numbers, and Bernoulli numbers.|A006882 (n!!), A006894 (3-trees), A006966 (lattices), A007318 (Pascal's triangle), A008275 (Stirling 1), A008277 (Stirling 2), A008279 (permutations k at a time), A008292 (Eulerian), A008683 (Moebius), A010060 (Thue-Morse), A018252 (nonprimes), A020639 (smallest prime factor), A020652 (fractal), A020653 (fractal), A025487 (prime sigs.), A027641 (Bernoulli), A027642 (Bernoulli), A035099 (j_2), A038566 (fractal), A038567 (fractal), A038568 (fractal), A038569 (fractal), A049310 (Chebyshev), A055512 (lattices)
|11. Factorization & Structure: The anatomy of multiplication. A deeper look into how numbers break down, focusing on Prime Signatures, Factorizations, and binary lengths.|A070939 (binary length), A074206 (ordered factorizations), A104725 (complementing systems), , A226898 (Hooley's Delta), A246655 (prime powers)



## Fibonacci

斐波那契数列背后机制来自 7/9 个模块, 最典型的“全栈序列”。

1. ODE: 𝐸′′= 𝐸′+ 𝐸
2. Matrix: ([1,1][1,0])^n
3. Group action: 自由幺半群上的字计数
4. Zeta: Dirichlet series → polylog
5. Graph: path graph 的独立集数
6. AG代数几何: 某些椭圆曲线 Frobenius eigenvalues = φ
7. Representation: TL algebra、任何子群表示维数

| 机制类别         | 斐波那契出现方式                       |
| ------------ | ------------------------------ |
| **微分方程**     | 指数生成函数满足二阶 ODE                 |
| **矩阵**       | 2×2 矩阵幂、特征值 φ                  |
| **群作用**      | Burnside计数、tiling               |
| **zeta**     | Dirichlet 级数、Liₛ(φ)            |
| **模形式**      | Lambert series → mock modular  |
| **图论（额外机制）** | path graph 独立集、匹配数             |
| **代数几何**     | 椭圆曲线 Frobenius eigenvalues     |
| **表示论**      | Fibonacci anyons、TL algebra 分支 |
| **同调计数**     | Betti 数 obey Fibonacci         |


In [ ]:
# Fibonacci sequence

# 0) Simple recurrence (baseline)
def fib_rec(n):
    if n < 0:
        return 0
    a,b = 0,1
    for _ in range(n):
        a,b = b,a+b
    return a

# 1) 2x2 Matrix power (Binet via eigenvalues)
Q = Matrix([[1,1],[1,0]])

def fib_matrix(n):
    if n==0:
        return 0
    M = Q**(n-1)   # Q^{n-1} * [F1; F0] = [Fn; F_{n-1}]
    return M[0,0]

# 2) Generating function viewpoint (algebraic OGF and EGF ODE)
# Ordinary generating function G(x) = x/(1 - x - x^2) satisfies algebraic equation
# (1 - x - x^2) * G(x) = x
# Exponential generating function E(x) = sum_{n>=0} F_n x^n / n! satisfies a linear ODE with lower-order correction terms:
# E'' - E' - E = c0 + c1*x^{-1} terms coming from initial indices; we verify numerically for coefficients.

def ogf_series(N=20):
    x = var('x')
    G = x/(1 - x - x^2)
    return G.series(x, N)

# Verify EGF differential relation numerically by power series

def egf_series_check(N=12):
    x = var('x')
    # build EGF as formal series using fib_rec
    E = sum(fib_rec(n)*x**n/factorial(n) for n in range(N))
    L = derivative(E, x, 2) - derivative(E, x, 1) - E
    return (E.series(x, N), L.series(x, N))

# 3) Combinatorial / tilings (group action & tiling)
# Number of ways to tile a 1 x n board with 1x1 and 1x2 tiles equals F_{n+1}

def tilings_count(n):
    # simple DP: ways[n] = ways[n-1] + ways[n-2]
    ways = [1,1]  # ways[0]=1 (empty), ways[1]=1
    for k in range(2, n+1):
        ways.append(ways[-1] + ways[-2])
    return ways[n]

# 4) Graph-theoretic: number of independent sets in path graph P_n equals F_{n+2}

def indep_sets_path(n):
    # DP: a_n = a_{n-1} + a_{n-2} with initial a_0 = 1, a_1 = 2
    a = [1,2]
    for k in range(2, n+1):
        a.append(a[-1] + a[-2])
    return a[n]

# 5) Dirichlet / zeta-style generating function (numerical exploration)
def dirichlet_F(s, terms=2000):
    # D(s) = sum_{n>=1} F_n / n^s
    return sum(Integer(fib_rec(n))*n**(-s) for n in range(1, terms))

# 6) Lambert series exploration: L(q) = sum_{n>=1} F_n q^n / (1 - q^n)
# numeric series evaluation for |q|<1

def lambert_series(q, terms=200):
    q = QQ(q)
    S = 0
    for n in range(1, terms):
        S += fib_rec(n)*q**n/(1 - q**n)
    return S

# 7) Temperley-Lieb / anyon-style fusion spaces (representation-theoretic viewpoint)
# Fibonacci anyon fusion dimensions satisfy the same recurrence:
# dim(n) = dim(n-1) + dim(n-2), with dim(0)=1, dim(1)=1 (or other base depending on boundary conditions)

def fusion_dim(n):
    return fib_rec(n+1)  # depending on indexing conventions

# 8) Elliptic-curve / Frobenius eigenvalue toy: Lucas sequences from trace of Frobenius
# This is a short demonstration: many linear recurrences (including Fibonacci/Lucas) arise from traces of Frobenius
# for rank-1 motives. We show a small example computing #E(F_p) for a curve and forming a_n = p + 1 - #E(F_p).

def frobenius_trace_sequence(curve, primes_list):
    seq = []
    for p in primes_list:
        Fp = GF(p)
        try:
            E = EllipticCurve(Fp, curve.a4(), curve.a6())
        except Exception:
            # Try different constructor
            E = EllipticCurve(Fp, curve['a'], curve['b'])
        ap = p + 1 - E.count_points()
        seq.append(ap)
    return seq

# Helper: small test suite that prints comparisons up to n
if __name__ == '__main__':
    N = 16
    print('n, fib_rec, fib_matrix, tilings (F_{n+1}), indep_sets_path (F_{n+2})')
    for n in range(N):
        print(n, fib_rec(n), fib_matrix(n), tilings_count(n-1) if n>=1 else 1, indep_sets_path(n))

    print('\nOGF series (first terms):')
    print(ogf_series(10))

    print('\nEGF check (E, L = E\'\' - E\' - E):')
    E_series, L_series = egf_series_check(10)
    print(E_series)
    print(L_series)

    # numeric Dirichlet demo (s=2)
    print('\nDirichlet partial sum D(2) (200 terms):', dirichlet_F(2, terms=200))

    # Lambert numeric demo q=1/2
    print('\nLambert partial sum q=1/2 (100 terms):', lambert_series(1/2, terms=100))

    # fusion dims
    print('\nFusion dims (first 10):', [fusion_dim(i) for i in range(10)])

    # Note: For serious research-level identifications (modular/elliptic-curve identifications,
    # or rigorous relations to mock modular forms / polylogarithms) one typically uses
    # symbolic/analytic number theory tools and references. This script provides
    # computational experiments and demonstrations showing that many mathematical
    # structures produce the Fibonacci recurrence or Fibonacci-indexed counts.


n, fib_rec, fib_matrix, tilings (F_{n+1}), indep_sets_path (F_{n+2})
0 0 0 1 1
1 1 1 1 2
2 1 1 1 3
3 2 2 2 5
4 3 3 3 8
5 5 5 5 13
6 8 8 8 21
7 13 13 13 34
8 21 21 21 55
9 34 34 34 89
10 55 55 55 144
11 89 89 89 233
12 144 144 144 377
13 233 233 233 610
14 377 377 377 987
15 610 610 610 1597

OGF series (first terms):
1*x + 1*x^2 + 2*x^3 + 3*x^4 + 5*x^5 + 8*x^6 + 13*x^7 + 21*x^8 + 34*x^9 + Order(x^10)

EGF check (E, L = E'' - E' - E):
1*x + 1/2*x^2 + 1/3*x^3 + 1/8*x^4 + 1/24*x^5 + 1/90*x^6 + 13/5040*x^7 + 1/1920*x^8 + 17/181440*x^9 + Order(x^10)
(-11/8064)*x^8 + (-17/181440)*x^9 + Order(x^10)

Dirichlet partial sum D(2) (200 terms): 1.1656326168936983e+37

Lambert partial sum q=1/2 (100 terms): 302995815195050532457545218214614502310932491141181798461132696069181764110084972778811698328250879692773157223535174979540366288073965956765561873852076335961768472401593715677776856282635407906691772854133402063184304837052135267259545726193989220468119383429410547215669694471485324336065437602

In [ ]:
# FIBONACCI NUMBERS: F_0=0, F_1=1, F_n = F_{n-1} + F_{n-2}

print("="*70)
print("FIBONACCI NUMBERS")
print("="*70)

# --- 1. Direct Computation ---
print("\n1. First 20 Fibonacci numbers:")
fibs = [fibonacci(n) for n in range(20)]
print(fibs)

# --- 2. ODE / RECURRENCE RELATION ---
print("\n2. ODE CONNECTION: y'' = y' + y")
print("   Characteristic equation: λ² = λ + 1")
print("   Solutions: λ = (1 ± √5)/2 (golden ratio φ and conjugate)")

phi = (1 + sqrt(5))/2
psi = (1 - sqrt(5))/2

print(f"\n   Golden ratio φ = {phi.n(digits=10)}")
print(f"   Conjugate ψ = {psi.n(digits=10)}")

def fibonacci_binet(n):
    """Binet's formula: F_n = (φ^n - ψ^n)/√5"""
    phi = (1 + sqrt(5))/2
    psi = (1 - sqrt(5))/2
    return ((phi^n - psi^n)/sqrt(5)).simplify_full()

print("\n   Via Binet's formula (closed form from ODE):")
fibs_binet = [fibonacci_binet(n) for n in range(10)]
print(f"   {fibs_binet}")

# Verify it matches
print(f"   Match? {all(fibonacci_binet(n) == fibonacci(n) for n in range(15))}")

# --- 3. MATRIX POWERS ---
print("\n3. MATRIX: Powers of [[1,1],[1,0]]")

F = matrix([[1, 1], [1, 0]])
print(f"   Fibonacci matrix F = ")
print(F)

print("\n   Powers of F:")
for n in range(1, 8):
    Fn = F^n
    print(f"   F^{n} = {Fn.list()}, F_{n} = {Fn[0,1]}, F_{n+1} = {Fn[0,0]}")

# Eigenvalues are φ and ψ
print("\n   Eigenvalues of F:")
eigenvals = F.eigenvalues()
print(f"   {[e.n(digits=10) for e in eigenvals]}")
print(f"   These are φ and ψ!")

# Diagonalization: F = PDP^(-1)
print("\n   Diagonalization F = PDP⁻¹:")
P, D = F.eigenmatrix_right()
print(f"   P = {P}")
print(f"   D = {D}")
print(f"   Verify: F = PDP⁻¹? {F == P*D*P^(-1)}")

# --- 4. GENERATING FUNCTION ---
print("\n4. GENERATING FUNCTION: F(x) = x/(1-x-x²)")

R.<x> = PowerSeriesRing(QQ, default_prec=20)
F_gen = x/(1 - x - x^2)
print(f"   F(x) = {F_gen}")
print(f"   Coefficients: {F_gen.list()}")

# Verify partial fractions (from ODE eigenvalues)
print("\n   Partial fraction decomposition (using φ, ψ):")
print(f"   F(x) = 1/√5 * [1/(1-φx) - 1/(1-ψx)]")
x = var('x')

phi = (1 + sqrt(5))/2
psi = (1 - sqrt(5))/2

F_partial = (1/sqrt(5)) * ( 1/(1 - phi*x) - 1/(1 - psi*x) )
print(F_partial.series(x, 15))  # expand as a power series about x=0 up to x^14

# --- 5. CONTINUED FRACTIONS ---
print("\n5. CONTINUED FRACTIONS: φ = [1; 1, 1, 1, 1, ...]")

cf = continued_fraction(phi)
print(f"   Golden ratio as continued fraction: {cf}")
print(f"   First 15 convergents:")

for i in range(15):
    conv = cf.convergent(i)
    print(f"   p_{i}/q_{i} = {conv} = {conv.numerator()}/{conv.denominator()}", end="")
    if i > 0:
        print(f" → Ratio of F_{i+1}/F_{i}")
    else:
        print()

# --- 6. GROUP THEORY / WORD STRUCTURES ---
print("\n6. GROUP THEORY: Fibonacci counts in free monoid")
print("   Words of length n using {a, b} with no consecutive b's")

def count_no_consecutive_b(n, memo={0: 1, 1: 2}):
    """Count binary strings of length n with no consecutive 1's (or b's)"""
    if n in memo:
        return memo[n]
    # Either ends in 'a' (0) or 'b' (1)
    # If ends in 'a': previous n-1 can be anything
    # If ends in 'b': previous must end in 'a', so n-2 positions
    result = count_no_consecutive_b(n-1, memo) + count_no_consecutive_b(n-2, memo)
    memo[n] = result
    return result

print(f"   Counts: {[count_no_consecutive_b(n) for n in range(12)]}")
print(f"   These are F_{n+2}!")

# --- 7. TILINGS ---
print("\n7. TILINGS: Ways to tile 1×n board with 1×1 and 1×2 tiles")

def count_tilings(n, memo={0: 1, 1: 1}):
    """Count ways to tile 1×n board"""
    if n in memo:
        return memo[n]
    # Either place 1×1 tile (leaving n-1) or 1×2 tile (leaving n-2)
    result = count_tilings(n-1, memo) + count_tilings(n-2, memo)
    memo[n] = result
    return result

tilings = [count_tilings(n) for n in range(15)]
print(f"   Tiling counts: {tilings}")
print(f"   These are Fibonacci numbers!")

# --- 8. MODULAR ARITHMETIC (Pisano Periods) ---
print("\n8. MODULAR ARITHMETIC: Fibonacci mod m (Pisano periods)")

def pisano_period(m):
    """Find period of Fibonacci sequence mod m"""
    prev, curr = 0, 1
    for i in range(m * m):
        prev, curr = curr, (prev + curr) % m
        if prev == 0 and curr == 1:
            return i + 1
    return -1

print("   Pisano periods π(m) for small m:")
for m in range(2, 13):
    period = pisano_period(m)
    fib_mod = [fibonacci(n) % m for n in range(period)]
    print(f"   π({m:2d}) = {period:3d}, sequence mod {m}: {fib_mod[:min(12, period)]}") 

FIBONACCI NUMBERS

1. First 20 Fibonacci numbers:
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]

2. ODE CONNECTION: y'' = y' + y
   Characteristic equation: λ² = λ + 1
   Solutions: λ = (1 ± √5)/2 (golden ratio φ and conjugate)

   Golden ratio φ = 1.618033989
   Conjugate ψ = -0.6180339888

   Via Binet's formula (closed form from ODE):
   [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
   Match? True

3. MATRIX: Powers of [[1,1],[1,0]]
   Fibonacci matrix F = 
[1 1]
[1 0]

   Powers of F:
   F^1 = [1, 1, 1, 0], F_1 = 1, F_2 = 1
   F^2 = [2, 1, 1, 1], F_2 = 1, F_3 = 2
   F^3 = [3, 2, 2, 1], F_3 = 2, F_4 = 3
   F^4 = [5, 3, 3, 2], F_4 = 3, F_5 = 5
   F^5 = [8, 5, 5, 3], F_5 = 5, F_6 = 8
   F^6 = [13, 8, 8, 5], F_6 = 8, F_7 = 13
   F^7 = [21, 13, 13, 8], F_7 = 13, F_8 = 21

   Eigenvalues of F:
   [-0.6180339888, 1.618033989]
   These are φ and ψ!

   Diagonalization F = PDP⁻¹:
   P = [-0.618033988749895?                   0]
[                  0  1.618033988749

## Prime counting

In [ ]:
# PRIME COUNTING AND RELATED FUNCTIONS

print("\n" + "="*70)
print("PRIME COUNTING FUNCTIONS")
print("="*70)

# --- 1. π(x): Prime Counting Function ---
print("\n1. π(x): Number of primes ≤ x")

x_vals = [10, 50, 100, 500, 1000, 5000, 10000]
print("\n   x       π(x)    x/ln(x)   li(x)      Ratio π(x)/li(x)")
print("   " + "-"*65)

for x in x_vals:
    pi_x = prime_pi(x)
    x_over_logx = x/log(x)
    li_x = Li(x).n()
    ratio = float(pi_x/li_x)
    print("   %5s   %5s   %10.4f   %10.4f   %.6f" %
          (x, pi_x, x_over_logx, li_x, ratio))
print("\n   Note: li(x) = integral from 0 to x of dt/ln(t)")
print("   π(x) ~ li(x) as x → ∞ (Prime Number Theorem)")

# --- 2. RIEMANN ZETA FUNCTION ---
print("\n2. RIEMANN ZETA FUNCTION: ζ(s) = Σ 1/n^s = ∏ 1/(1-p^(-s))")

print("\n   Values at integers:")
for s in range(2, 8):
    zeta_val = zeta(s)
    print(f"   ζ({s}) = {zeta_val.n(digits=15)}")

print(f"\n   ζ(2) = π²/6 = {(pi^2/6).n(digits=15)}")
print(f"   ζ(4) = π⁴/90 = {(pi^4/90).n(digits=15)}")

# Euler product
print("\n   Euler product for ζ(2) using first 10 primes:")
primes_list = primes_first_n(10)
euler_product = prod(1/(1 - p^(-2)) for p in primes_list)
print(f"   ∏ 1/(1-p^(-2)) ≈ {euler_product.n(digits=10)}")
print(f"   Actual ζ(2) = {zeta(2).n(digits=10)}")

# --- 3. VON MANGOLDT FUNCTION Λ(n) ---
print("\n3. VON MANGOLDT FUNCTION: Λ(n)")
print("   Λ(n) = log(p) if n = p^k for prime p, else 0")

def von_mangoldt(n):
    """von Mangoldt function"""
    if n <= 1:
        return 0
    f = factor(n)
    if len(f) == 1:  # Prime power
        p, k = f[0]
        return log(p)
    return 0

print("\n   n:  ", list(range(1, 21)))
mangoldt_vals = [von_mangoldt(n) for n in range(1, 21)]
print("   Λ(n):", [float(v.n(digits=3)) if v != 0 else 0 for v in mangoldt_vals])

# Chebyshev functions
print("\n   Chebyshev ψ(x) = Σ_{n≤x} Λ(n)")
def chebyshev_psi(x):
    return sum(von_mangoldt(n) for n in range(1, x+1))

for x in [10, 50, 100, 500]:
    psi_x = chebyshev_psi(x)
    ratio = float(psi_x/x)
    print(f"   ψ({x:3d}) = {psi_x.n(digits=6):8.2f}, ψ(x)/x = {ratio:.6f}")

print(f"   Note: ψ(x)/x → 1 as x → ∞ (equivalent to PNT)")

# --- 4. MÖBIUS FUNCTION μ(n) ---
print("\n4. MÖBIUS FUNCTION: μ(n)")
print("   μ(n) = 1 if n is square-free with even # of prime factors")
print("   μ(n) = -1 if n is square-free with odd # of prime factors")
print("   μ(n) = 0 if n is not square-free")

print("\n   n:  ", list(range(1, 21)))
mobius_vals = [moebius(n) for n in range(1, 21)]
print("   μ(n):", mobius_vals)

# Möbius inversion
print("\n   Möbius inversion: Σ_{d|n} μ(d) = [n=1]")
for n in [1, 6, 12, 30]:
    divisor_sum = sum(moebius(d) for d in divisors(n))
    print(f"   n={n:2d}: Σ μ(d) = {divisor_sum}")

# Mertens function
print("\n   Mertens function M(x) = Σ_{n≤x} μ(n)")
def mertens(x):
    return sum(moebius(n) for n in range(1, x+1))

mertens_vals = [mertens(10^k) for k in range(1, 5)]
print(f"   M(10^k): {mertens_vals}")
print(f"   Riemann Hypothesis ⟺ M(x) = O(x^(1/2 + ε))")

# --- 5. DIRICHLET L-FUNCTIONS ---
print("\n5. DIRICHLET L-FUNCTIONS (generalizations of ζ)")
print("   Example: L(s, χ₄) where χ₄ is character mod 4")
print("   χ₄(n) = 0 if n even, 1 if n≡1 (mod 4), -1 if n≡3 (mod 4)")

def chi_4(n):
    """Dirichlet character mod 4"""
    if n % 2 == 0:
        return 0
    elif n % 4 == 1:
        return 1
    else:
        return -1

print(f"\n   χ₄(n) for n=1..16: {[chi_4(n) for n in range(1, 17)]}")

# L(1, χ₄) = π/4 (related to Leibniz formula for π)
print(f"\n   L(1, χ₄) = Σ χ₄(n)/n = π/4")
L_approx = sum(chi_4(n)/n for n in range(1, 10001) if chi_4(n) != 0)
print(f"   Partial sum (10000 terms): {L_approx.n(digits=10)}")
print(f"   π/4 = {(pi/4).n(digits=10)}")

# --- 6. PRIME GAPS ---
print("\n6. PRIME GAPS: g_n = p_{n+1} - p_n")

gaps = []
prev_p = 2
for i, p in enumerate(primes(100)):
    if i > 0:
        gaps.append(p - prev_p)
    prev_p = p

print(f"   First 25 prime gaps: {gaps[:25]}")
print(f"   Average gap: {float(mean(gaps[:25])):.2f}")

# Cramér's conjecture
print(f"\n   Cramér's conjecture: g_n = O((log p_n)²)")
p_100 = nth_prime(100)
print(f"   p_100 = {p_100}, (log p_100)² = {(log(p_100)^2).n(digits=4)}")

# --- 7. TWIN PRIMES ---
print("\n7. TWIN PRIMES: Primes p where p+2 is also prime")

twin_primes = [(p, p+2) for p in primes(200) if is_prime(p+2)]
print(f"   First 15 twin prime pairs:")
for i, (p1, p2) in enumerate(twin_primes[:15]):
    print(f"   ({p1:3d}, {p2:3d})", end="  ")
    if (i+1) % 5 == 0:
        print()

# Twin prime constant
print(f"\n   Twin prime conjecture: infinitely many twin primes")
print(f"   If true, # of twin primes < x ~ 2C₂ x/(ln x)²")
print(f"   where C₂ ≈ 0.66016... is the twin prime constant")

# --- 8. EXPLICIT FORMULA (Riemann-von Mangoldt) ---
print("\n8. EXPLICIT FORMULA: Connects primes to zeta zeros")
print("   ψ(x) = x - Σ_ρ (x^ρ/ρ) - log(2π)")
print("   where ρ are non-trivial zeros of ζ(s)")

print("\n   First few non-trivial zeros (on critical line Re(s)=1/2):")
print("   (Computing these requires numerical methods)")
print("   ρ₁ ≈ 1/2 + 14.134725i")
print("   ρ₂ ≈ 1/2 + 21.022040i")
print("   ρ₃ ≈ 1/2 + 25.010858i")

print("\n   The distribution of primes is intimately connected")
print("   to the distribution of zeta zeros!")

# --- 9. ADJACENCY MATRIX OF PRIME GRAPH ---
print("\n9. MATRIX: Adjacency matrix of prime graph")
print("   Connect primes p, q if p+q is also prime")

small_primes = primes_first_n(8)
n = len(small_primes)
A = matrix(ZZ, n, n)

for i in range(n):
    for j in range(n):
        if i != j and is_prime(small_primes[i] + small_primes[j]):
            A[i, j] = 1

print(f"   Primes: {small_primes}")
print(f"   Adjacency matrix:")
print(A)
print(f"   Eigenvalues: {[e.n(digits=6) for e in A.eigenvalues()]}")

print("\n" + "="*70)
print("From discrete recurrences to continuous analysis:")
print("The golden thread connecting algebra, analysis, and number theory!")
print("="*70)


PRIME COUNTING FUNCTIONS

1. π(x): Number of primes ≤ x

   x       π(x)    x/ln(x)   li(x)      Ratio π(x)/li(x)
   -----------------------------------------------------------------
      10       4       4.3429       5.1204   0.781184
      50      15      12.7811      17.4235   0.860905
     100      25      21.7147      29.0810   0.859668
     500      95      80.4556     100.7487   0.942940
    1000     168     144.7648     176.5645   0.951494
    5000     669     587.0479     683.2357   0.979164
   10000    1229    1085.7362    1245.0921   0.987076

   Note: li(x) = integral from 0 to x of dt/ln(t)
   π(x) ~ li(x) as x → ∞ (Prime Number Theorem)

2. RIEMANN ZETA FUNCTION: ζ(s) = Σ 1/n^s = ∏ 1/(1-p^(-s))

   Values at integers:
   ζ(2) = 1.64493406684823
   ζ(3) = 1.20205690315959
   ζ(4) = 1.08232323371114
   ζ(5) = 1.03692775514337
   ζ(6) = 1.01734306198445
   ζ(7) = 1.00834927738192

   ζ(2) = π²/6 = 1.64493406684823
   ζ(4) = π⁴/90 = 1.08232323371114

   Euler product for ζ(

/tmp/ipykernel_53915/86190811.py:130: DeprecationWarning: sage.stats.basic_stats.mean is deprecated; use numpy.mean or numpy.nanmean instead
See https://github.com/sagemath/sage/issues/29662 for details.
  print(f"   Average gap: {float(mean(gaps[:Integer(25)])):.2f}")


## Catalan

In [ ]:
# CATALAN NUMBERS: C_n = (1/(n+1)) * binomial(2n, n)

print("="*70)
print("CATALAN NUMBERS")
print("="*70)

# --- 1. Direct Computation ---
def catalan(n):
    return binomial(2*n, n) / (n+1)

catalans = [catalan(n) for n in range(10)]
print("\n1. First 10 Catalan numbers:")
print(catalans)

# --- 2. RECURRENCE / ODE Connection ---
print("\n2. RECURRENCE (ODE discrete analog):")
print("   C_0 = 1, C_{n+1} = sum_{i=0}^{n} C_i * C_{n-i}")

def catalan_recurrence(n, memo={0: 1}):
    if n in memo:
        return memo[n]
    result = sum(catalan_recurrence(i, memo) * catalan_recurrence(n-1-i, memo) 
                 for i in range(n))
    memo[n] = result
    return result

catalans_rec = [catalan_recurrence(n) for n in range(10)]
print("   Via recurrence:", catalans_rec)
print("   Match direct?", catalans == catalans_rec)

# --- 3. MATRIX: Hankel Matrix ---
print("\n3. MATRIX: Hankel matrix of Catalan numbers")
n = 5
H = matrix([[catalan(i+j) for j in range(n)] for i in range(n)])
print(H)
print(f"   Determinant: {H.determinant()}")
print(f"   Rank: {H.rank()}")

# --- 4. GENERATING FUNCTION ---
print("\n4. GENERATING FUNCTION: C(x) = (1 - sqrt(1-4x))/(2x)")
R.<x> = PowerSeriesRing(QQ, default_prec=10)
C = (1 - sqrt(1 - 4*x))/(2*x)
print(f"   C(x) = {C}")
print(f"   Coefficients: {C.list()}")

# Verify functional equation: C(x) = 1 + x*C(x)^2
C_squared = (1 + x*C^2).add_bigoh(10)
print(f"   Check C = 1 + xC²: {C == C_squared}")

# --- 5. SYMMETRY: Count Dyck paths via automaton ---
print("\n5. SYMMETRY/COMBINATORICS: Dyck paths of length 2n")
print("   (Paths from (0,0) to (2n,0) with steps ±1, never going below 0)")

def count_dyck_paths(n):
    """Count Dyck paths using dynamic programming"""
    if n == 0:
        return 1
    # dp[i][j] = number of paths of length i ending at height j
    dp = [[0]*(n+1) for _ in range(2*n+1)]
    dp[0][0] = 1
    
    for i in range(2*n):
        for j in range(n+1):
            if dp[i][j] > 0:
                # Can go up if not at max height
                if j < n:
                    dp[i+1][j+1] += dp[i][j]
                # Can go down if not at ground
                if j > 0:
                    dp[i+1][j-1] += dp[i][j]
    
    return dp[2*n][0]

dyck_counts = [count_dyck_paths(n) for n in range(8)]
print(f"   Dyck path counts: {dyck_counts}")

# --- 6. 312-AVOIDING PERMUTATIONS (Group theory) ---
print("\n6. GROUP THEORY: 312-avoiding permutations in S_n")
def is_312_avoiding(perm):
    """Check if permutation avoids pattern 312"""
    n = len(perm)
    for i in range(n):
        for j in range(i+1, n):
            for k in range(j+1, n):
                if perm[i] < perm[k] < perm[j]:
                    return False
    return True

for n in range(1, 6):
    P = Permutations(n)
    count = sum(1 for p in P if is_312_avoiding(p))
    print(f"   n={n}: {count} permutations (Catalan C_{n-1})")

CATALAN NUMBERS

1. First 10 Catalan numbers:
[1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862]

2. RECURRENCE (ODE discrete analog):
   C_0 = 1, C_{n+1} = sum_{i=0}^{n} C_i * C_{n-i}
   Via recurrence: [1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862]
   Match direct? True

3. MATRIX: Hankel matrix of Catalan numbers
[   1    1    2    5   14]
[   1    2    5   14   42]
[   2    5   14   42  132]
[   5   14   42  132  429]
[  14   42  132  429 1430]
   Determinant: 1
   Rank: 5

4. GENERATING FUNCTION: C(x) = (1 - sqrt(1-4x))/(2x)
   C(x) = 1 + x + 2*x^2 + 5*x^3 + 14*x^4 + 42*x^5 + 132*x^6 + 429*x^7 + 1430*x^8 + O(x^9)
   Coefficients: [1, 1, 2, 5, 14, 42, 132, 429, 1430]
   Check C = 1 + xC²: True

5. SYMMETRY/COMBINATORICS: Dyck paths of length 2n
   (Paths from (0,0) to (2n,0) with steps ±1, never going below 0)
   Dyck path counts: [1, 1, 2, 5, 14, 42, 132, 429]

6. GROUP THEORY: 312-avoiding permutations in S_n
   n=1: 1 permutations (Catalan C_0)
   n=2: 2 permutations (Catalan C_1)
   n=3: 5

## Partition

In [ ]:
# PARTITION FUNCTION: p(n) = number of ways to write n as sum of positive ints
print("\n" + "="*70)
print("PARTITION FUNCTION")
print("="*70)

# --- 1. Direct Computation ---
print("\n1. First 15 partition numbers:")
partitions = [Partitions(n).cardinality() for n in range(15)]
print(partitions)

# --- 2. RECURRENCE (Euler's Pentagonal Number Theorem) ---
print("\n2. RECURRENCE: Euler's pentagonal number theorem")
print("   p(n) = p(n-1) + p(n-2) - p(n-5) - p(n-7) + p(n-12) + ...")
print("   Using pentagonal numbers k(3k-1)/2 for k = ±1, ±2, ±3, ...")

def partition_euler(n, memo={0: 1}):
    if n < 0:
        return 0
    if n in memo:
        return memo[n]
    
    result = 0
    k = 1
    while True:
        pent1 = k*(3*k - 1)//2
        pent2 = k*(3*k + 1)//2
        
        if pent1 > n:
            break
            
        sign = (-1)^(k+1)
        result += sign * partition_euler(n - pent1, memo)
        
        if pent2 <= n:
            result += sign * partition_euler(n - pent2, memo)
        
        k += 1
    
    memo[n] = result
    return result

partitions_euler = [partition_euler(n) for n in range(15)]
print(f"   Via Euler recurrence: {partitions_euler}")
print(f"   Match direct? {partitions == partitions_euler}")

# --- 3. GENERATING FUNCTION ---
print("\n3. GENERATING FUNCTION: Product formula")
print("   1/((1-x)(1-x²)(1-x³)...) = sum p(n)x^n")

R.<x> = PowerSeriesRing(QQ, default_prec=15)
# Compute product up to degree 14
P = prod(1/(1-x^k) for k in range(1, 15))
print(f"   Coefficients: {P.list()}")

# --- 4. MATRIX: Ferrers Diagrams ---
print("\n4. MATRIX: Ferrers diagram for partition [5,3,3,1]")
partition = [5, 3, 3, 1]
max_width = max(partition)
ferrers = matrix([[1 if j < partition[i] else 0 
                   for j in range(max_width)] 
                  for i in range(len(partition))])
print(ferrers)
print(f"   Sum of entries: {sum(sum(row) for row in ferrers)} = {sum(partition)}")

# Conjugate partition (transpose)
conjugate = ferrers.transpose()
print("\n   Conjugate partition (transpose):")
print(conjugate)
conj_parts = [sum(conjugate.column(i)) for i in range(conjugate.ncols())]
print(f"   Conjugate partition: {conj_parts}")

# --- 5. GROUP THEORY: Conjugacy classes in S_n ---
print("\n5. GROUP THEORY: Partitions label conjugacy classes in S_n")

for n in range(1, 7):
    G = SymmetricGroup(n)
    conj_classes = G.conjugacy_classes()
    print(f"   S_{n} has {len(conj_classes)} conjugacy classes = p({n}) = {Partitions(n).cardinality()}")
    
    if n == 5:
        print(f"   Example: S_5 conjugacy class representatives:")
        for cc in conj_classes[:5]:  # Show first 5
            rep = cc.representative()
            cycle_type = rep.cycle_type()
            print(f"      Cycle type {cycle_type}: size {cc.cardinality()}")

# --- 6. YOUNG TABLEAUX (Representation Theory) ---
print("\n6. REPRESENTATION THEORY: Young tableaux")
print("   Standard Young tableaux for partition [3,2]:")

partition_shape = [3, 2]
tableaux = StandardTableaux(partition_shape)
print(f"   Number of standard tableaux: {tableaux.cardinality()}")
print("   First few tableaux:")
for i, t in enumerate(tableaux):
    if i >= 3:
        break
    print(f"\n   Tableau {i+1}:")
    for row in t:
        print(f"      {row}")

# --- 7. ZETA CONNECTION: Asymptotic formula ---
print("\n7. ZETA/ANALYTIC: Hardy-Ramanujan asymptotic formula")
print("   p(n) ~ (1/(4n*sqrt(3))) * exp(pi*sqrt(2n/3))")

def hardy_ramanujan_approx(n):
    if n == 0:
        return 1
    return (1/(4*n*sqrt(3))) * exp(pi*sqrt(2*n/3))

print("\n   n    p(n)      Approximation     Ratio")
print("   " + "-"*50)
for n in [10, 20, 30, 50, 100]:
    exact = Partitions(n).cardinality()
    approx = hardy_ramanujan_approx(n)
    ratio = float(exact/approx)
    print("   %3s  %8s  %13.1f     %.6f" %
        (n, exact, approx, ratio))
print("\n" + "="*70)
print("The unity of mathematics: sequences as windows into structure!")
print("="*70)



PARTITION FUNCTION

1. First 15 partition numbers:
[1, 1, 2, 3, 5, 7, 11, 15, 22, 30, 42, 56, 77, 101, 135]

2. RECURRENCE: Euler's pentagonal number theorem
   p(n) = p(n-1) + p(n-2) - p(n-5) - p(n-7) + p(n-12) + ...
   Using pentagonal numbers k(3k-1)/2 for k = ±1, ±2, ±3, ...
   Via Euler recurrence: [1, 1, 2, 3, 5, 7, 11, 15, 22, 30, 42, 56, 77, 101, 135]
   Match direct? True

3. GENERATING FUNCTION: Product formula
   1/((1-x)(1-x²)(1-x³)...) = sum p(n)x^n
   Coefficients: [1, 1, 2, 3, 5, 7, 11, 15, 22, 30, 42, 56, 77, 101, 135]

4. MATRIX: Ferrers diagram for partition [5,3,3,1]
[1 1 1 1 1]
[1 1 1 0 0]
[1 1 1 0 0]
[1 0 0 0 0]
   Sum of entries: 12 = 12

   Conjugate partition (transpose):
[1 1 1 1]
[1 1 1 0]
[1 1 1 0]
[1 0 0 0]
[1 0 0 0]
   Conjugate partition: [5, 3, 3, 1]

5. GROUP THEORY: Partitions label conjugacy classes in S_n
   S_1 has 1 conjugacy classes = p(1) = 1
   S_2 has 2 conjugacy classes = p(2) = 2
   S_3 has 3 conjugacy classes = p(3) = 3
   S_4 has 5 conjugac

## FindStat

OEIS and FindStat

Combine of Seq:   → New Seq without point
  - Seq + Seq: a(n) + b(n)
  - Seq × Seq: a(n) * b(n)

Combine of Statistic:   → New Stat with point
  - Stat + Stat: (f + g)(x) = f(x) + g(x)
  - Stat ∘ Stat: (f ∘ map)(x)
  - co-Stat: (f, g)(x) = (f(x), g(x))

**FindStat to OEIS**

FindStat对象             |→   主导OEIS生成机制
|- | -|
Permutations             |  → 3,7,9,6
ASMs                     |  → 7,9,8
Integer partitions       |  → 6,1,8
Dyck paths / Catalan类   |  → 1,2,3,7
Binary words             |  → 1,2
Integer compositions     |  → 1,2,3
Ordered trees            |  → 1,7,3
Parking functions        |  → 3,9,6
Cores / Finite Cartan    |  → 4,9,3,6
Gelfand–Tsetlin patterns |  → 2,9
Graphs / matchings       |  → 7,2,9
Lattices                 |  → 4,3
Ordered set partitions   |  → 6,3

## Common operations


>> **Docker pull**

My phone internet limitation, so I can't use usual docker pull. Instead, use [docker-drag](https://github.com/heran226813/docker-drag). 
Open terminal, example: 
- `python3 docker_pull.py sagemath`
- `docker load -i sagemath.tar`
- `docker run -it sagemath`

>> **Image-Hosting**

All figures are synchronised in Tom's GitHub folder `./NB_img/`. Using codes to insert pic:

`<img src="https://raw.githubusercontent.com/tomctang/NB_img/main/3bias.png" alt="Causality-confounder" width="500">`

Markdown image **center**:

`<div align=center>![Figure. Various treatments choice for OA](https://raw.githubusercontent.com/ctang83/NB_img/main/EPS_OAtreat.jpg){width=60%}`

>> **Cross-citations**

Header automatically generate {#mathFP}, so`[anytext](#mathFP)` in citing

Between pages: `[Discrete & Continuous](../10pe/02discrete_continuous.ipynb#discrete-continuous)`(ipynb auto changed to html in website)